### ISSUE TITLE
anchor = null

### ISSUE THREAD

**Issue by Ritterrh** [Abedalkareem/games_services#178]
This happens with everything except the login
E/flutter (23482): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(failed_to_show_achievements, 4: , null, null)
E/flutter (23482): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter (23482): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (23482): <asynchronous suspension>
E/flutter (23482): #2      MethodChannelGamesServices.showAchievements (package:games_services_platform_interface/src/game_services_platform_impl.dart:41:12)
E/flutter (23482): <asynchronous suspension>
E/flutter (23482): #3      Achievements.showAchievements (package:games_services/src/achievements.dart:10:12)
E/flutter (23482): <asynchronous suspension>
E/flutter (23482): #4      _HomePageState._unlock (package:BommChain/views/home_screen.dart:163:5)
E/flutter (23482): <asynchronous suspension>
E/flutter (23482):

**Comment by theLee3** [comment]
Is the game in testing or release? If testing, is the user added as a tester?

**Comment by Abedalkareem** [comment]
This is a very common issue `(code 4:)` please make sure that your app configured correctly.
