### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Jhon2524** [Abedalkareem/games_services#28]
I followed all the instructions.

Updated the manifest, connected my app to firebase,
linked and updated sha1 and sha256,
added test device,
requested authorization and updated the onauth screen from the google console api,
despite that I still have this annoying error 👍 

`
I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): Failed to silent signin, trying explicit signin I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): com.google.android.gms.common.api.ApiException: 4: 4: I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.1.0:4) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at com.google.android.gms.common.internal.zai.zaf(com.google.android.gms:play-services-base@@17.1.0:2) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at com.google.android.gms.common.internal.zak.onComplete(com.google.android.gms:play-services-base@@17.1.0:6) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at com.google.android.gms.common.api.internal.BasePendingResult.zaa(com.google.android.gms:play-services-base@@17.1.0:176) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at com.google.android.gms.common.api.internal.BasePendingResult.setResult(com.google.android.gms:play-services-base@@17.1.0:135) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at com.google.android.gms.auth.api.signin.internal.zzi.zzc(com.google.android.gms:play-services-auth@@18.1.0:5) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at com.google.android.gms.auth.api.signin.internal.zzs.zzc(com.google.android.gms:play-services-auth@@18.1.0:6) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at com.google.android.gms.internal.auth-api.zzc.onTransact(com.google.android.gms:play-services-auth@@18.1.0:13) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at android.os.Binder.execTransactInternal(Binder.java:1021) I/xyz.luan.games.play.playgames.PlayGamesPlugin(27003): at android.os.Binder.execTransact(Binder.java:994) W/ActivityThread(27003): handleWindowVisibility: no activity for token android.os.BinderProxy@4fd66b7 I/flutter (27003): ERROR Unexpected error Status{statusCode=unknown status code: 12501, resolution=null}`

anyone else in my situation?
thanks

**Comment by Pielgrin** [comment]
Hello @Jhon2524, I am in the same situation. Have you resolved this problem ?
Thanks

**Comment by Abedalkareem** [comment]
Hi,

Have you done this part?

```
You do need to enable the OAuth APIs that you want, using the Google Cloud Platform API manager. You’ll need also to enable the Google People API.
Make sure you’ve filled out all required fields in the console for OAuth consent screen. Otherwise, you may encounter APIException errors.
```

Please try to follow this tutorial
https://itnext.io/how-to-integrate-gamekit-and-google-play-services-flutter-4d3f4a4a2f77

**Comment by wrteam-priyansh** [comment]
@Jhon2524 @Pielgrin have you found the solution for this login error. i am still getting this error..

**Comment by Pielgrin** [comment]
Hi @Abedalkareem, @wrteam-priyansh 
I still face this issue and try to fix it.
I noticed yesterday that my application was affiliated to several Google Cloud projects. So I deleted one and ask for OAuth consent one more time, I am waiting for Google's validation. When they will grant me access, I will try again and let you know 😉.

**Comment by Pielgrin** [comment]
Hello @wrteam-priyansh Google approved oauth consent but the problem still remain...
Tell me if you find a solution

**Comment by Pielgrin** [comment]
@Abedalkareem @wrteam-priyansh 
I finally found the solution !
I was doing this : 
`<meta-data android:name="com.google.android.gms.games.APP_ID"
            android:value="MYAPPID" />`

Instead of this : 
`<meta-data android:name="com.google.android.gms.games.APP_ID"
            android:value="@string/app_id" />`
with a xml file (that I called games-ids.xml inside of android/app/src/main/res/values) with this content : 
`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_id">MYAPPID</string>
</resources>`

**Comment by kajack** [comment]
Facing the same issue. Any other clue that it can lead to a fix? Been to many hours stuck at the same step without any sense...

**Comment by Abedalkareem** [comment]
Hi guys, 
Please be aware that this kind of issues related to something wrong with the configurations.
I suggest to check the tutorial and try to find out what is the small mistake (usually small) that make this issue.

Thank you for your support!!

**Comment by ItzcoR** [comment]
> @Abedalkareem @wrteam-priyansh
> I finally found the solution !
> I was doing this :
> `<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="MYAPPID" />`
> 
> Instead of this :
> `<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="@string/app_id" />`
> with a xml file (that I called games-ids.xml inside of android/app/src/main/res/values) with this content :
> `<?xml version="1.0" encoding="utf-8"?> <resources> <string name="app_id">MYAPPID</string> </resources>`

I had this error 
`E/Error   (14281): signInError
E/Error   (14281): com.google.android.gms.common.api.ApiException: 8: 8: 
E/Error   (14281): 	at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.4.0:4)
E/Error   (14281): 	at com.google.android.gms.common.internal.zan.zaa(com.google.android.gms:play-services-base@@17.4.0:2)
E/Error   (14281): 	at com.google.android.gms.common.internal.zap.onComplete(com.google.android.gms:play-services-base@@17.4.0:6)
E/Error   (14281): 	at com.google.android.gms.common.api.internal.BasePendingResult.zab(com.google.android.gms:play-services-base@@17.4.0:177)
E/Error   (14281): 	at com.google.android.gms.common.api.internal.BasePendingResult.setResult(com.google.android.gms:play-services-base@@17.4.0:136)
E/Error   (14281): 	at com.google.android.gms.auth.api.signin.internal.zzk.zzc(com.google.android.gms:play-services-auth@@19.0.0:5)
E/Error   (14281): 	at com.google.android.gms.auth.api.signin.internal.zzu.zzc(com.google.android.gms:play-services-auth@@19.0.0:6)
E/Error   (14281): 	at com.google.android.gms.internal.auth-api.zzc.onTransact(com.google.android.gms:play-services-auth@@19.0.0:13)
E/Error   (14281): 	at android.os.Binder.execTransact(Binder.java:697)
I/ExplicitSignIn(14281): Trying explicit sign in
D/EGL_emulation(14281): eglMakeCurrent: 0xa4486920: ver 3 0 (tinfo 0x8bb944d0)
I/silentSignIn(14281): error
E/flutter (14281): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, Something went wrong Status{statusCode=INTERNAL_ERROR, resolution=null}, null, null)
E/flutter (14281): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
E/flutter (14281): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (14281): <asynchronous suspension>
E/flutter (14281): #2      MethodChannelGamesServices.signIn (package:games_services_platform_interface/method_channel_games_services.dart:46:14)
E/flutter (14281): <asynchronous suspension>
E/flutter (14281): #3      GamesServices.signIn (package:games_services/games_services.dart:58:12)
E/flutter (14281): <asynchronous suspension>
E/flutter (14281): `
It was also solved by changing this

**Comment by kajack** [comment]
@ItzcoR Changing what exactly? What you quoted?

**Comment by ItzcoR** [comment]
@kajack ye, by changing what I quoted

**Comment by EliaTolin** [comment]
@ItzcoR Have you fix problem?

**Comment by drobyshys** [comment]
still have same errors

**Comment by victormanuelfrancodev** [comment]
I had this error... then doesn't have solution?
