### ISSUE TITLE
SignIn exception

### ISSUE THREAD

**Issue by EliaTolin** [Abedalkareem/games_services#52]
Hi,

I follow the instruction but I have this problem.

E/Error   (13180): signInError
E/Error   (13180): com.google.android.gms.common.api.ApiException: 10: 10:
E/Error   (13180): 	at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@18.0.0:3)
E/Error   (13180): 	at com.google.android.gms.common.internal.zap.onComplete(com.google.android.gms:play-services-base@@18.0.0:4)
E/Error   (13180): 	at com.google.android.gms.common.api.internal.BasePendingResult.zab(com.google.android.gms:play-services-base@@18.0.0:7)
E/Error   (13180): 	at com.google.android.gms.common.api.internal.BasePendingResult.setResult(com.google.android.gms:play-services-base@@18.0.0:6)
E/Error   (13180): 	at com.google.android.gms.auth.api.signin.internal.zbf.zbd(com.google.android.gms:play-services-auth@@19.2.0:3)
E/Error   (13180): 	at com.google.android.gms.auth.api.signin.internal.zbq.zba(com.google.android.gms:play-services-auth@@19.2.0:7)
E/Error   (13180): 	at com.google.android.gms.internal.auth-api.zbb.onTransact(com.google.android.gms:play-services-auth@@19.2.0:3)
E/Error   (13180): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
E/Error   (13180): 	at android.os.Binder.execTransact(Binder.java:1123)
I/ExplicitSignIn(13180): Trying explicit sign in
I/silentSignIn(13180): error

Have you suggest for me?

**Comment by EliaTolin** [comment]
I solved it, just simply wait a minute for the services to load, then the login screen is shown.
