### ISSUE TITLE
 Error in getPlayerId

### ISSUE THREAD

**Issue by M4rc0b** [Abedalkareem/games_services#60]
Hi All,

I'm getting this error in production, have you any suggestions? 
Thanks

```
Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:14)
       at com.abedalkareem.games_services.GamesServicesPlugin.getPlayerID$lambda-2(GamesServicesPlugin.java:17)
       at com.abedalkareem.games_services.GamesServicesPlugin.lambda$ZT9IoZ9Yl1eW2EUSiGsMyIYy45I(GamesServicesPlugin.java)
       at com.abedalkareem.games_services.-$$Lambda$GamesServicesPlugin$ZT9IoZ9Yl1eW2EUSiGsMyIYy45I.onFailure(-.java:2)
       at com.google.android.gms.tasks.zzk.run(zzk.java:30)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by Abedalkareem** [comment]
This will happen if this line called twice 
```
result.success(it)
```
This line in the plugin so there is nothing to do from your side. 

Are you logging in before calling it? can you give me steps of what are you doing?
If someone can reproduce that it will help a lot to fix the issue.

**Comment by M4rc0b** [comment]
Unfortunately I can't reproduce this error, It happens only in production, for some Android devices. 
I have only one point where I call getPlayerId, where every time I save a score I call before 
**await GamesServices.isSignedIn** 
and then 
**await GamesServices.getPlayerID()**
Now I'm testing a different approach, and I'm trying to cache the playerId, after signedIn method, so I don't have to call GamesServices.isSignedIn every time.
About the Exception I have only the log on Firebase Crashlytics, and the list of involved devices.

**Comment by M4rc0b** [comment]
I don't know exactly the reason, but avoiding every time to call these methods in sequence, caching the player id after login, the error is disappeared.
Thanks

**Comment by Abedalkareem** [comment]
I tried to reproduce this issue multiple times with no luck, please if anyone can add steps to reproduce that will help a lot.
